### ISSUE TITLE
Provider crashes with latest xenolf/lego and latest Terraform

### ISSUE THREAD

**Issue by idcmp** [terraform-providers/terraform-provider-acme#8]
The current version of `t-p-a` does not correct provision wildcard certificates when using NS1 as a DNS provider. I've gotten `xenolf/lego` fixed upstream, and switched `Gopkg.toml` to using `master` of lego and `v0.11.8` of `hashicorp/terraform` (the version I'm running). 

This causes Terraform to crash:

```
2018/10/02 17:58:27 [DEBUG] apply: acme_certificate.certificate: executing Apply
2018-10-02T17:58:28.974-0700 [DEBUG] plugin.terraform-provider-acme_v1.0.1_x4: panic: interface conversion: interface {} is schema.Set, not *schema.Set
2018-10-02T17:58:28.974-0700 [DEBUG] plugin.terraform-provider-acme_v1.0.1_x4:
2018-10-02T17:58:28.974-0700 [DEBUG] plugin.terraform-provider-acme_v1.0.1_x4: goroutine 60 [running]:
2018-10-02T17:58:28.974-0700 [DEBUG] plugin.terraform-provider-acme_v1.0.1_x4: github.com/terraform-providers/terraform-provider-acme/vendor/github.com/hashicorp/terraform/helper/schema.(*MapFieldWriter).setSet(0xc420317400, 0xc42061f930, 0x1, 0x1, 0x1d4c560, 0xc420317460, 0xc42052e870, 0x0, 0xffffffffffffffff)
2018-10-02T17:58:28.974-0700 [DEBUG] plugin.terraform-provider-acme_v1.0.1_x4: 	/home/idcmp/go/src/github.com/terraform-providers/terraform-provider-acme/vendor/github.com/hashicorp/terraform/helper/schema/field_writer_map.go:343 +0xa63
2018-10-02T17:58:28.974-0700 [DEBUG] plugin.terraform-provider-acme_v1.0.1_x4: github.com/terraform-providers/terraform-provider-acme/vendor/github.com/hashicorp/terraform/helper/schema.(*MapFieldWriter).set(0xc420317400, 0xc42061f930, 0x1, 0x1, 0x1d4c560, 0xc420317460, 0x0, 0x0)
2018-10-02T17:58:28.974-0700 [DEBUG] plugin.terraform-provider-acme_v1.0.1_x4: 	/home/idcmp/go/src/github.com/terraform-providers/terraform-provider-acme/vendor/github.com/hashicorp/terraform/helper/schema/field_writer_map.go:107 +0x2ac
```

**Comment by vancluever** [comment]
@idcmp this should be fixed in the next provider release, thanks for reporting!
